version: '3.0'

services:
  server:
    build: ./server   
    ports:
      - "5000:5000"
    depends_on:
      - mongo   
    
  mongo:
    image: mongo    
    ports:
      - "27017:27017"

  client:
    build: ./client      
    depends_on:
      - server
    ports:
      - "3000:3000"
    